name: ESLint

on:
    workflow_dispatch:
    pull_request:
    push:
      branches:
        - '*'
        - '!gh-pages'

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    test:
      name: ESLint
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Install Node v18
          uses: actions/setup-node@v4
          with:
            node-version: 18

        - name: Install dependencies
          run: npm ci

        - name: Run ESLint
          run: npm run lint

        - name: Build
          run: npm run build

        - name: Run Unit Tests
          run: npm run test
